export const GET_INDUSTRY_LIST = "GET_INDUSTRY_LIST";
export const GET_INDUSTRY_DETAIL = "GET_INDUSTRY_DETAIL";
export const GET_SKILL_LIST = "GET_SKILL_LIST";
export const GET_SKILL_DETAIL = "GET_SKILL_DETAIL";

export const GET_ADVERTISEMENT_LIST = "GET_ADVERTISEMENT_LIST";
export const GET_ADVERTISEMENT_DETAIL = "GET_ADVERTISEMENT_DETAIL";

export const GET_JOB_TYPE_LIST = "GET_JOB_TYPE_LIST";
export const GET_JOB_TYPE_DETAIL = "GET_JOB_TYPE_DETAIL";

export const GET_LEVEL_LIST = "GET_LEVEL_LIST";
export const GET_LEVEL_DETAIL = "GET_LEVEL_DETAIL";

export const GET_CITY_PROVINCE_LIST = "GET_CITY_PROVINCE_LIST";
export const GET_CITY_PROVINCE_DETAIL = "GET_CITY_PROVINCE_DETAIL";
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_LOCATION_DETAIL = "GET_LOCATION_DETAIL";

export const GET_SUBSCRIPTION_PLAN_LIST = "GET_SUBSCRIPTION_PLAN_LIST";
export const GET_SUBSCRIPTION_PLAN_DETAIL = "GET_SUBSCRIPTION_PLAN_DETAIL";
export const GET_SUBSCRIPTION_PLAN_BY_ACCOUNT = "GET_SUBSCRIPTION_PLAN_BY_ACCOUNT";
export const GET_SUBSCRIPTION_PLAN_FROM_ADMIN_BY_ID_ACCOUNT = "GET_SUBSCRIPTION_PLAN_FROM_ADMIN_BY_ID_ACCOUNT";


export const GET_JOB_LIST = "GET_JOB_LIST";
export const GET_JOB_DETAIL = "GET_JOB_DETAIL";
export const GET_APPLICATION_BY_JOB = "GET_APPLICATION_BY_JOB";
export const GET_CV_SAVED = "GET_CV_SAVED";

// export const GET_APPLICATION_BY_JOB = "GET_APPLICATION_BY_JOB";



export const GET_CHART_OF_EMPLOYER = "GET_CHART_OF_EMPLOYER";
export const GET_CHART_OF_EMPLOYER_BY_ID = "GET_CHART_OF_EMPLOYER_BY_ID";
export const GET_CHART_OF_ADMIN = "GET_CHART_OF_ADMIN";

export const GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
export const GET_ACCOUNT_CANDIDATE_LIST = "GET_ACCOUNT_CANDIDATE_LIST";
export const GET_ACCOUNT_EMPLOYER_LIST = "GET_ACCOUNT_EMPLOYER_LIST";
export const GET_ACCOUNT_WITHOUT_COMPANY = "GET_ACCOUNT_WITHOUT_COMPANY";
export const GET_ACCOUNT_DETAIL = "GET_ACCOUNT_DETAIL";
export const GET_EMPLOYER_COMPANY_DETAIL = "GET_EMPLOYER_COMPANY_DETAIL";
export const GET_COMPANY_BY_ACCOUNT_ID = "GET_COMPANY_BY_ACCOUNT_ID";


export const GET_COMPANY_JOB = "GET_COMPANY_JOB";
export const GET_COMPANY_LIST = "GET_COMPANY_LIST";
export const GET_COMPANY_DETAIL = "GET_COMPANY_DETAIL";
export const GET_DATA_CHART_BY_COMPANYID_OF_EMPLOYER = "GET_DATA_CHART_BY_COMPANYID_OF_EMPLOYER";
export const GET_COMPANY_FOR_EMPLOYER_FROM_ADMIN = "GET_COMPANY_FOR_EMPLOYER_FROM_ADMIN";
export const GET_SEARCH_COMPANY_JOB_ACCOUNT = "GET_SEARCH_COMPANY_JOB_ACCOUNT";
export const GET_FOLLOW_COMPANY_BY_CANDIDATE = "GET_FOLLOW_COMPANY_BY_CANDIDATE";


//--------------------------------------------------------------
export const GET_ENABLE_BUS_LIST = "GET_ENABLE_BUS_LIST";
export const GET_BUS_DETAIL = "GET_BUS_DETAIL";
export const GET_BUS_TYPE_LIST = "GET_BUS_TYPE_LIST";
export const GET_BUS_TYPE_DETAIL = "GET_BUS_TYPE_DETAIL";


export const GET_DRIVER_LIST = "GET_DRIVER_LIST";
export const GET_REGISTER_DRIVER_LIST = "GET_REGISTER_DRIVER_LIST";
export const GET_DRIVER_DETAIL = "GET_DRIVER_DETAIL";


export const GET_STATION_LIST = "GET_STATION_LIST";
export const GET_STATION_DETAIL = "GET_STATION_DETAIL";


export const GET_TRIP_LIST = "GET_TRIP_LIST";
export const GET_TRIP_DETAIL = "GET_TRIP_DETAIL";
export const GET_PROMOTE_TRIP_LIST = "GET_PROMOTE_TRIP_LIST";
export const GET_PROMOTE_TRIP_DETAIL = "GET_PROMOTE_TRIP_DETAIL";


export const GET_NEWS_LIST = "GET_NEWS_LIST";
export const GET_NEWS_DETAIL = "GET_NEWS_DETAIL";


export const GET_OFFER_LIST = "GET_OFFER_LIST";
export const GET_ENABLE_OFFER_LIST = "GET_ENABLE_OFFER_LIST";
export const GET_OFFER_DETAIL = "GET_OFFER_DETAIL";
export const GET_OFFER_BY_CODE = "GET_OFFER_BY_CODE";


export const LOGIN_ACTION = "LOGIN_ACTION";
export const REGISTER_ACTION = "REGISTER_ACTION";
export const LAY_LAI_MAT_KHAU_ACTION = "LAY_LAI_MAT_KHAU_ACTION";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_CURRENT_USER_ACTION = "GET_CURRENT_USER_ACTION";
export const GET_PROFILE_DETAIL = "GET_PROFILE_DETAIL";
export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG";
export const GET_MOD_LIST = "GET_MOD_LIST";
export const GET_MOD_DETAIL = "GET_MOD_DETAIL";


export const GET_FAQ_LIST = "GET_FAQ_LIST";
export const GET_FAQ_DETAIL = "GET_FAQ_DETAIL";


export const CHON_GHE = "CHON_GHE";
export const ORDER_CONFIRM = "ORDER_CONFIRM";
export const DAT_VE = "DAT_VE";
export const DELETE_SELECTING_SEATS = "DELETE_SELECTING_SEATS";
export const GET_TICKET_RESULT = "GET_TICKET_RESULT";
export const GET_TICKET_BY_USER = "GET_TICKET_BY_USER";
export const GET_TICKET_BY_CUSTOMER = "GET_TICKET_BY_CUSTOMER";
export const GET_TICKET_STATUS = "GET_TICKET_STATUS";
export const DELETE_TICKET_DETAIL = "DELETE_TICKET_DETAIL";


export const GET_PROFIT_BY_ROUTE = "GET_PROFIT_BY_ROUTE";
export const GET_PROFIT_BY_MONTH = "GET_PROFIT_BY_MONTH";

export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const CHUYEN_TAB = "CHUYEN_TAB";
export const CHUYEN_TAB_ACTIVE = "CHUYEN_TAB_ACTIVE";

